export const rolesData = [
  {
    id: 1,
    roleName: 'Dealer',
    permissions: 'Module 1, Module 2, Module 3, Module 4',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: true,
  },
  {
    id: 2,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: false,
  },
  {
    id: 3,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: true,
  },
  {
    id: 4,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: false,
  },
  {
    id: 5,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: true,
  },
  {
    id: 6,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: false,
  },
  {
    id: 7,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: true,
  },
  {
    id: 8,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: false,
  },
  {
    id: 9,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: true,
  },
  {
    id: 10,
    roleName: 'Role Name Here',
    permissions: '--',
    createdDate: '22 Feb 2024',
    createdTime: '11:40:42 AM',
    status: false,
  },
];

export const headerConfig = [
  {
    key: 'roleName',
    label: 'Role Name',
    sortable: true,
    width: '200px',
  },
  {
    key: 'permissions',
    label: 'Permissions',
    sortable: false,
    width: '300px',
  },
  {
    key: 'status',
    label: 'Status',
    sortable: true,
    width: '100px',
    type: 'toggle',
  },
  {
    key: 'action',
    label: 'Action',
    sortable: false,
    width: '80px',
    type: 'action',
  },
];

export const PERMISSIONS = {
  'module 1': [
    'Permission 1',
    'Permission 2',
    'Permission 3',
    'Permission 4',
    'Permission 5',
    'Permission 6',
  ],
  'module 2': [
    'Permission 1',
    'Permission 2',
    'Permission 3',
    'Permission 4',
    'Permission 5',
    'Permission 6',
  ],
  'module 3': [
    'Permission 1',
    'Permission 2',
    'Permission 3',
    'Permission 4',
    'Permission 5',
    'Permission 6',
  ],
  'module 4': [
    'Permission 1',
    'Permission 2',
    'Permission 3',
    'Permission 4',
    'Permission 5',
    'Permission 6',
  ],
  'module 5': [
    'Permission 1',
    'Permission 2',
    'Permission 3',
    'Permission 4',
    'Permission 5',
    'Permission 6',
  ],
  'module 6': [
    'Permission 1',
    'Permission 2',
    'Permission 3',
    'Permission 4',
    'Permission 5',
    'Permission 6',
  ],
};

// Dealer Management Table Data
export const dealerManagementHeaderConfig = [
  { key: 'fullName', label: 'Dealer Name' },
  { key: 'email', label: 'Email' },
  { key: 'listing', label: 'Listing' },
  { key: 'sold', label: 'Sold' },
  { key: 'sellRate', label: 'Sell Rate (%)' },
  { key: 'lastActive', label: 'Last Active' },
  { key: 'isActive', label: 'Status' },
  { key: 'action', label: 'Action' },
];
